[package]
name = "rlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.8.0"
walkdir = "2.3.2"
fs_extra = "1.2.0"
